export const COMMON = {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
};
export const AUTH = {
  SIGNIN_SCREEN: 'SIGNIN_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  REGISTER_OTP_SCREEN: 'REGISTER_OTP_SCREEN',
};
export const BodyScreen = {
  //homeScreen
  HOME_SCREEN: 'HOME_SCREEN',
  HOME_WASTE_SCREEN: 'HOME_WASTE_SCREEN',
  PURCHASE_OPERATIONS_SCREEN: 'PURCHASE_OPERATIONS_SCREEN',

  //moreScreen
  MORE_SCREEN: 'MORE_SCREEN',
  SUPPORT_SCREEN: 'SUPPORT_SCREEN',
  TERMS_SCREEN: 'TERMS_SCREEN',
  MY_ADDRESS_SCREEN: 'MY_ADDRESS_SCREEN',
  HISTORY_SCREEN: 'HISTORY_SCREEN',
};
export const SCREEN_MAIN = 'SCREEN_MAIN';
